<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>brain</artifactId>
        <groupId>com.gxpublish</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>brain-demo</module>
        <module>brain-generator</module>
        <module>brain-job</module>
        <module>brain-system</module>
        <module>brain-workflow</module>
        <module>brain-editorial</module>
    </modules>

    <artifactId>brain-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        brain-modules 业务模块
    </description>

</project>

