<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.gxpublish</groupId>
        <artifactId>brain-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>brain-demo</artifactId>

    <description>
        demo模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-mail</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-idempotent</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-log</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-excel</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-ratelimiter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-translation</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-sensitive</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-encrypt</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>com.gxpublish</groupId>
            <artifactId>brain-common-websocket</artifactId>
        </dependency>

    </dependencies>

</project>

